###
#用户登录测试
POST http://localhost:8080/jwt/login?userName=haha&passWord=123
Accept: */*
Cache-Control: no-cache
###

###
#随意测试一个需要 Token 验证的接口
GET http://localhost:8080/jwt/info
Accept: */*
Cache-Control: no-cache
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiaWF0IjoxNjA2MjY5NDM5LCJleHAiOjE2MDYyNzMwMzl9.XaTOcKZ5T5HH9Az1AsMd508SOuLGOCjx-1bLfqTcOEUo5AHzNqV2JmtVKn2r2zNRNzp9MNIc_YzPlmDdkLPK5A
###

#根据请求头的token获取userId
GET http://localhost:8080/jwt/getUserInfo
Accept: */*
Cache-Control: no-cache
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiaWF0IjoxNjA2MjAzNTIzLCJleHAiOjE2MDYyMDcxMjN9.1hS1g9wiwYcQK3ZZPyQcb67e6KNDhIhKob-LWOVpFImtRa4OFKiMI2F2hZfR9sVTDqD_Tt4XM_5AAGuAx7rgew
###