###
#用户登录测试
POST http://localhost:8080/jwt/login?userName=haha&passWord=123
Accept: */*
Cache-Control: no-cache
###

###
#随意测试一个需要 Token 验证的接口
GET http://localhost:8080/jwt/info
Accept: */*
Cache-Control: no-cache
token: eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiI1IiwiaWF0IjoxNjA3MDYwMDA5LCJleHAiOjE2MDcwNjM2MDl9.xAY7R2xn2obpllluSnh0WTOcqrUdOERyVTovzMRbOm7iVditHrDS6YPWhP-J6B_RGDLKR41VHULHwBG0YdZOxg

###

#根据请求头的token获取userId
GET http://localhost:8080/jwt/getUserInfo
Accept: */*
Cache-Control: no-cache
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiaWF0IjoxNjA2MjAzNTIzLCJleHAiOjE2MDYyMDcxMjN9.1hS1g9wiwYcQK3ZZPyQcb67e6KNDhIhKob-LWOVpFImtRa4OFKiMI2F2hZfR9sVTDqD_Tt4XM_5AAGuAx7rgew
###